swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transaction:
    get:
      security:
        - Bearer: [ ]
      tags:
        - Transactions Module
      summary: User transactions
      description: API for fetching user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Unauthorized access, invalid token
        '403':
          description: Forbidden, access denied
        '500':
          description: Internal Server Error
  /transaction/{transactionId}:
    get:
      security:
        - Bearer: [ ]
      tags:
        - Transactions Module
      summary: Transaction
      description: API for fetching one user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the transaction to get
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/SingleTransaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized access, invalid token
        '403':
          description: Forbidden, access denied
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: [ ]
      tags:
        - Transactions Module
      summary: Transaction
      description: API for adding new informations to a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the transaction to which information is added
        - in: body
          name: body
          description: Transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionDetails'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction informations added successully
          schema:
            $ref: '#/definitions/SingleTransaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized access, invalid token
        '403':
          description: Forbidden, access denied
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: [ ]
      tags:
        - Transactions Module
      summary: Transaction
      description: API for updating a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the transaction to which information is updated
        - in: body
          name: body
          description: Transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionDetails'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction informations updated successully
          schema:
            $ref: '#/definitions/SingleTransaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized access, invalid token
        '403':
          description: Forbidden, access denied
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: [ ]
      tags:
        - Transactions Module
      summary: Transaction
      description: API for deleting a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the transaction to which information is deleted
      produces:
        - application/json
      responses:
        '204':
          description: User transaction informations deleted successully
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized access, invalid token
        '403':
          description: Forbidden, access denied
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    type: array
    items:
      type: object
      properties:
        userId:
          type: integer
          readOnly: true
        transactionId:
          type: integer
          readOnly: true
        date:
          type: string
          format: date
          readOnly: true
        description:
          type: string
          readOnly: true
        amount:
          type: number
          readOnly: true
  SingleTransaction:
    type: object
    properties:
      transactionId:
        type: integer
        readOnly: true
      date:
        type: string
        format: date
        readOnly: true
      description:
        type: string
        readOnly: true
      amount:
        type: number
        readOnly: true
      transactionType:
        type: string
        readOnly: true
      category:
        type: string
      notes:
        type: string
  TransactionDetails:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string